config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :posts
  root to: 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    #Tagsテーブルから中間テーブルに対する関連付け
    has_many :tweet_tag_relations, dependent: :destroy
    #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
    has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_many :tweet_tag_relations, dependent: :destroy
    has_many :tags, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      tweet = Tweet.find(params[:tweet_id])
      comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
 def index
 end
 
 def link
 end   

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
    end
  
    def new
      @post = Post.new
    end
  
    def show
      @post = Post.find_by(id: params[:id])
    end

    def create
        @post = Post.new(post_params)
        params[:post][:question] ? @post.question = params[:post][:question].join("") : false
        if @post.save
            flash[:notice] = "診断が完了しました"
            redirect_to post_path(@post.id)
        else
            redirect_to :action => "new"
        end
      end
    
    private
      def post_params
          params.require(:post).permit(:id, question: [])
      end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
    def index
      if params[:tag_ids]
        @tweets = []
        params[:tag_ids].each do |key, value|      
          @tweets += Tag.find_by(name: key).tweets if value == "1"
        end
        @tweets.uniq!
      end
      @tweets = Tweet.page(params[:page]).per(3)

    end
    def new
        @tweet = Tweet.new
      end
      def create
        tweet = Tweet.new(tweet_params)
        tweet.user_id = current_user.id 
        if tweet.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    def show
        @tweet = Tweet.find(params[:id])
        @comments = @tweet.comments
        @comment = Comment.new
    end
    def edit
      @tweet = Tweet.find(params[:id])
    end
    def update
      tweet = Tweet.find(params[:id])
      if tweet.update(tweet_params)
        redirect_to :action => "show", :id => tweet.id
      else
        redirect_to :action => "new"
      end
    end
    def destroy
      tweet = Tweet.find(params[:id])
      tweet.destroy
      redirect_to action: :index
    end
      private
      def tweet_params
        params.require(:tweet).permit(:body, tag_ids: [])
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hello/index.html.erb
<%= link_to "ログイン", tweets_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/hello/link.html.erb
My name is Geeksalon
<%= link_to 'トップページ', hello_index_path %>
<%= link_to '一覧表示', tweets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geektwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/13b0a9e5f9.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   </head>

  <body>
  <header>
    <h1>GeekTwitter</h1>
    <div class="header-list">
    <ul>
      <li><%= link_to "ホーム", tweets_path %></li>
      <li><%= link_to "新規投稿",new_tweet_path %></li>
      <li><%= link_to "診断",posts_path %></li>
    </ul>
    </div>
  </header>
  <main>
    <%= yield %>
   </main>
   <footer>
    <p>Copyright © GeekSalon All Rights Reserved.</p>
   </footer>
  </body>
</html>

app/views/posts/index.html.erb
        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断を始める", new_post_path, class: "link" %>
        </div>

app/views/posts/new.html.erb
<%= form_for(@post, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="container-sindan">
        <div class="row">
            <div class="col-12">
                <p>Question1. どちらかと言うと…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>じっくり考える方だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>考えるより行動する方だ</p>
            </div>

            <div class="col-12">
                <p>Question2. 自分の価値観として近い方は…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>周りの人と違う存在でありたい</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>周りと同じでいたい</p>
            </div>

            <div class="col-12">
                <p>Question3. 人と接するときは…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>相手の話をよく聞く方だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>自分の話をよくする方だ</p>
            </div>

            <div class="col-12">
                <p>Question4. 大切にしたいのは…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>論理性だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>情緒だ</p>
            </div>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit "post" %>
    </div>
<% end %>

app/views/posts/show.html.erb
<div class="intoro">
            <h5>診断結果</h5>
            <p>あなたにおすすめの香りは…</p>
        </div>
        <div class="tweet-container">
            <div class="tweet">
                <% if @post.question == "1111" %>
                <h6>レモン</h6>
                <p>柑橘系の代表的な原料</p>
                <p>清涼感があり、爽やかな印象</p>

                <% elsif @post.question == "1112" %>
                <h6>シトラス</h6>
                <p>オレンジに似た柑橘系の果物</p>
                <p>リラックス効果がある</p>

                <% elsif @post.question == "1121" %>
                <h6>ローズ</h6>
                <p>華やかで上品な香り</p>
                <p>ストレスを緩和してくれる効果がある</p>

                <% elsif @post.question == "1122" %>
                <h6>ラベンダー</h6>
                <p>優しく女性らしい香り</p>
                <p>気持ちを落ち着かせてくれる</p>

                <% elsif @post.question == "1211" %>
                <h6>ジャスミン</h6>
                <p>爽やかなのに官能的な香り</p>
                <p>幸福感を得やすい</p>

                <% elsif @post.question == "1212" %>
                <h6>ピーチ</h6>
                <p>フレッシュで優しい香り</p>
                <p>アンチエイジングにも最適</p>

                <% elsif @post.question == "1221" %>
                <h6>アップル</h6>
                <p>特徴的で甘い香り</p>
                <p>万人受けしやすい</p>

                <% elsif @post.question == "1222" %>
                <h6>ユーカリ</h6>
                <p>しっかりとした優しい香り</p>
                <p>浄化作用があり。気持ちを落ち着かせてくれる</p>

                <% elsif @post.question == "2111" %>
                <h6>ローズマリー</h6>
                <p>きりりとした強めの香りが特徴的</p>
                <p>美容効果が高い</p>

                <% elsif @post.question == "2112" %>
                <h6>ベルガモット</h6>
                <p>柑橘系の果実</p>
                <p>甘くてフレッシュな、万能な香料</p>

                <% elsif @post.question == "2121" %>
                <h6>ムスク</h6>
                <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
                <p>官能的で重い香り</p>

                <% elsif @post.question == "2122" %>
                <h6>アンバー</h6>
                <p>マッコウクジラの結石から抽出した香料</p>
                <p>魅惑的で色気のある香り</p>

                <% elsif @post.question == "2211" %>
                <h6>シナモン</h6>
                <p>甘いスパイスの香り</p>
                <p>香水のアクセントとしてよく使われる</p>

                <% elsif @post.question == "2212" %>
                <h6>バニラ</h6>
                <p>甘くて官能的な香り</p>
                <p>上品で年齢を問わず人気が高い</p>

                <% elsif @post.question == "2221" %>
                <h6>イランイラン</h6>
                <p>色気のある濃厚で甘い香り</p>
                <p>恋愛に効果があり</p>

                <% elsif @post.question == "2222" %>
                <h6>サンダルウッド</h6>
                <p>お香としてよく使われる白檀の香り</p>
                <p>集中力を高める効果もあり</p>

                <% end %>

        </div>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/tweets/index.html.erb
Enjoy programming!
<%= link_to "新規投稿ページへ", new_tweet_path %>
<h1>GeekTwitter</h1>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<%= link_to "新規投稿へ", new_tweet_path %>
<%= stylesheet_link_tag 'index', :media => "all" %>
<%= page_entries_info @tweets %>
<%= paginate @tweets %>
<div class="tweets-container">
<h3>Tweet一覧</h3>
  <% @tweets.each do |t| %>
    <div class="tweet">
    <%= t.user.email %>
    <% if user_signed_in? %>
    <% if current_user.already_liked?(t) %>
        <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
    <% else %>
        <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
          <i class="far fa-heartstyle="color:red;"></i><%= t.likes.count %>
        <% end %>
    <% end %>
<% else %>
    <p>いいねの数 = </p><%= t.likes.count %>
<% end %>
      <div class="main-box">
        <div class="left-container"><%= t.body %></div>
        <div class="right-container">
          <%= link_to "詳細", tweet_path(t.id) %>
          <%= link_to "編集", edit_tweet_path(t.id) %>
          <%= link_to "削除", tweet_path(t.id), method: :delete %>
        </div>
  </div>
    <p class="time"><%= t.created_at %></p>
  </div>
    <% end %>
</div>
<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
  <% Tag.all.each do |t| %>
      <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
  <% end %>
  <%= submit_tag '検索' %>
<% end %>

app/views/tweets/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
    <p class="title">投稿フォーム</p>
    <%= form_for(@tweet, :url => { controller:'tweets', action:'create'})do |f| %>
    <%= f.label :投稿内容 %>
        <br>
        <%= f.text_field :body,size: 140%>
        <br>
        <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>
    <%= f.submit "送信"%>
    <br>
    <% end %>
</div>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
        <%= button_to tweet_like_path(@tweet), method: :delete do %>
          <p>いいねを取り消す</p><%= @tweet.likes.count %>
        <% end %>
      <% else %>
        <%= button_to tweet_likes_path(@tweet), method: :post do %>
          <p>いいね</p><%= @tweet.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @tweet.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
<% @tweet.tags.each do |tag| %>
  <span><%= tag.name %></span>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>